#!/bin/bash
if [ "$2" == "" ]; then
	echo "Convert an input audio file (e.g., WAV) to raw audio for the project."
	echo "$0 [input] [output]"
	echo
	echo "example: $0 foobar.wav foobar.raw"
	exit 1
fi

#sox "$1" -r 11025 -e unsigned -b 8 -c 1 -t raw "$2" fade 0.0002 -0 0.0002
sox "$1" -r 11025 -e unsigned -b 8 -c 1 -t raw "$2"
